/**
 * Document renderer — converts AI-generated text content into downloadable
 * Word (.docx) and PDF files for service deliverables (CVs, cover letters,
 * SOPs, motivation letters, etc.).
 *
 * Input format: plain text where blank lines separate paragraphs and lines
 * beginning with "# " / "## " are treated as headings. This matches the
 * shape gpt-4o-mini returns when asked for "a clean, ATS-friendly CV".
 *
 * Output: Node Buffer ready to be sent via res.send() with the appropriate
 * Content-Type and Content-Disposition headers.
 */

import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  TextRun,
  AlignmentType,
} from "docx";
import PDFDocument from "pdfkit";

export interface RenderInput {
  /** Plain-text body of the document (paragraphs separated by blank lines). */
  body: string;
  /** Optional title shown at the top of the document. */
  title?: string;
  /** Optional footer (e.g. "Generated by WorkAbroad Hub — workabroadhub.tech"). */
  footer?: string;
}

// ─── DOCX ──────────────────────────────────────────────────────────────────────

function bodyToDocxParagraphs(body: string): Paragraph[] {
  const lines = body.replace(/\r\n/g, "\n").split("\n");
  const paragraphs: Paragraph[] = [];

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) {
      paragraphs.push(new Paragraph({ children: [new TextRun("")] }));
      continue;
    }
    // Markdown-ish heading detection
    if (line.startsWith("### ")) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [new TextRun({ text: line.slice(4), bold: true })],
        }),
      );
    } else if (line.startsWith("## ")) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun({ text: line.slice(3), bold: true })],
        }),
      );
    } else if (line.startsWith("# ")) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun({ text: line.slice(2), bold: true })],
        }),
      );
    } else if (/^[*-]\s/.test(line)) {
      paragraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          children: [new TextRun(line.replace(/^[*-]\s/, ""))],
        }),
      );
    } else {
      // Bold spans wrapped in **...**
      const parts = line.split(/(\*\*[^*]+\*\*)/);
      const runs: TextRun[] = parts.map((p) =>
        p.startsWith("**") && p.endsWith("**")
          ? new TextRun({ text: p.slice(2, -2), bold: true })
          : new TextRun(p),
      );
      paragraphs.push(new Paragraph({ children: runs }));
    }
  }

  return paragraphs;
}

export async function renderDocx(input: RenderInput): Promise<Buffer> {
  const paragraphs: Paragraph[] = [];

  if (input.title) {
    paragraphs.push(
      new Paragraph({
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: input.title, bold: true })],
      }),
    );
    paragraphs.push(new Paragraph({ children: [new TextRun("")] })); // spacer
  }

  paragraphs.push(...bodyToDocxParagraphs(input.body));

  if (input.footer) {
    paragraphs.push(new Paragraph({ children: [new TextRun("")] }));
    paragraphs.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({
            text: input.footer,
            italics: true,
            color: "888888",
            size: 18, // half-points; 18 = 9pt
          }),
        ],
      }),
    );
  }

  const doc = new Document({
    creator: "WorkAbroad Hub",
    title: input.title ?? "WorkAbroad Hub Document",
    description: "AI-generated career document",
    sections: [{ children: paragraphs }],
  });

  return Packer.toBuffer(doc);
}

// ─── PDF ──────────────────────────────────────────────────────────────────────

export function renderPdf(input: RenderInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 50 });
      const chunks: Buffer[] = [];
      doc.on("data", (c) => chunks.push(c));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      if (input.title) {
        doc
          .font("Helvetica-Bold")
          .fontSize(20)
          .text(input.title, { align: "center" });
        doc.moveDown(1);
      }

      const lines = input.body.replace(/\r\n/g, "\n").split("\n");
      for (const raw of lines) {
        const line = raw.trim();
        if (!line) {
          doc.moveDown(0.5);
          continue;
        }
        // Headings — each one explicitly closes any previous text run by
        // setting continued:false (defensive against pdfkit state leak).
        if (line.startsWith("### ")) {
          doc.font("Helvetica-Bold").fontSize(12).text(line.slice(4), { continued: false });
          doc.moveDown(0.3);
        } else if (line.startsWith("## ")) {
          doc.font("Helvetica-Bold").fontSize(14).text(line.slice(3), { continued: false });
          doc.moveDown(0.3);
        } else if (line.startsWith("# ")) {
          doc.font("Helvetica-Bold").fontSize(16).text(line.slice(2), { continued: false });
          doc.moveDown(0.5);
        } else if (/^[*-]\s/.test(line)) {
          doc
            .font("Helvetica")
            .fontSize(11)
            .text("•  " + line.replace(/^[*-]\s/, ""), { continued: false });
        } else {
          // Render inline bold spans (**bold**). Filter empty fragments first,
          // then use index-based iteration to set continued correctly on the
          // FINAL part. Previously used indexOf() which returned the first
          // occurrence — when the line ended with a "**word**" span, the empty
          // trailing fragment got continued:true and bled into the next line.
          const parts = line
            .split(/(\*\*[^*]+\*\*)/)
            .filter((p) => p && p.length > 0);

          if (parts.length === 0) {
            doc.moveDown(0.5);
            continue;
          }

          parts.forEach((part, idx) => {
            const isBold = part.startsWith("**") && part.endsWith("**");
            const text = isBold ? part.slice(2, -2) : part;
            const isLastPart = idx === parts.length - 1;
            doc
              .font(isBold ? "Helvetica-Bold" : "Helvetica")
              .fontSize(11)
              .text(text, { continued: !isLastPart });
          });
        }
      }

      if (input.footer) {
        doc.moveDown(2);
        doc
          .font("Helvetica-Oblique")
          .fontSize(9)
          .fillColor("#888")
          .text(input.footer, { align: "center" });
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

function isLast<T>(arr: T[], item: T): boolean {
  return arr.indexOf(item) === arr.length - 1;
}
