/**
 * Document renderer — converts AI-generated text content into downloadable
 * Word (.docx) and PDF files for service deliverables (CVs, cover letters,
 * SOPs, motivation letters, etc.).
 *
 * Input format: plain text where blank lines separate paragraphs and lines
 * beginning with "# " / "## " are treated as headings. This matches the
 * shape gpt-4o-mini returns when asked for "a clean, ATS-friendly CV".
 *
 * Output: Node Buffer ready to be sent via res.send() with the appropriate
 * Content-Type and Content-Disposition headers.
 */

import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  TextRun,
  AlignmentType,
  ImageRun,
} from "docx";
import PDFDocument from "pdfkit";

export interface RenderInput {
  /** Plain-text body of the document (paragraphs separated by blank lines). */
  body: string;
  /** Optional title shown at the top of the document. */
  title?: string;
  /** Optional footer (e.g. "Generated by WorkAbroad Hub — workabroadhub.tech"). */
  footer?: string;
  /**
   * 2026-07 (Tony's founder request): optional passport-style photo to embed
   * at the top of the document. Should be a JPEG or PNG buffer, already
   * compressed to a reasonable size (~200-400 KB) by the client.
   *
   * When present, we render it top-right in the PDF (clipped to a rounded
   * square for a warmer feel than a hard rectangle) and top-right in the
   * DOCX (right-aligned paragraph before the body). When absent, the
   * document renders exactly as before.
   *
   * Rationale from founder: "I want our CVs not to be same as anyone.
   * The photo makes it feel real. Never generic."
   */
  photo?: {
    buffer: Buffer;
    /** Image mime — "image/jpeg" | "image/png" | "image/webp". Falls back to jpeg. */
    mimeType?: string;
  };
}

// ─── DOCX ──────────────────────────────────────────────────────────────────────

function bodyToDocxParagraphs(body: string): Paragraph[] {
  const lines = body.replace(/\r\n/g, "\n").split("\n");
  const paragraphs: Paragraph[] = [];

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) {
      paragraphs.push(new Paragraph({ children: [new TextRun("")] }));
      continue;
    }
    // Markdown-ish heading detection
    if (line.startsWith("### ")) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [new TextRun({ text: line.slice(4), bold: true })],
        }),
      );
    } else if (line.startsWith("## ")) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun({ text: line.slice(3), bold: true })],
        }),
      );
    } else if (line.startsWith("# ")) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun({ text: line.slice(2), bold: true })],
        }),
      );
    } else if (/^[*-]\s/.test(line)) {
      paragraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          children: [new TextRun(line.replace(/^[*-]\s/, ""))],
        }),
      );
    } else {
      // Bold spans wrapped in **...**
      const parts = line.split(/(\*\*[^*]+\*\*)/);
      const runs: TextRun[] = parts.map((p) =>
        p.startsWith("**") && p.endsWith("**")
          ? new TextRun({ text: p.slice(2, -2), bold: true })
          : new TextRun(p),
      );
      paragraphs.push(new Paragraph({ children: runs }));
    }
  }

  return paragraphs;
}

export async function renderDocx(input: RenderInput): Promise<Buffer> {
  const paragraphs: Paragraph[] = [];

  // 2026-07: photo goes FIRST — right-aligned so the recruiter sees the
  // candidate before the text. Fixed 100pt square (~1.4 inches) which is
  // the professional CV convention in most markets (UK/EU/Gulf/EAC).
  // Silently skipped when no photo — the doc is identical to the pre-2026
  // layout in that case.
  if (input.photo?.buffer && input.photo.buffer.length > 0) {
    try {
      // Detect type from mime so ImageRun picks the right decoder.
      const mime = (input.photo.mimeType || "image/jpeg").toLowerCase();
      const type: "jpg" | "png" =
        mime.includes("png") ? "png" : "jpg";
      paragraphs.push(
        new Paragraph({
          alignment: AlignmentType.RIGHT,
          children: [
            new ImageRun({
              data: input.photo.buffer,
              transformation: { width: 100, height: 100 },
              type,
            } as any),
          ],
        }),
      );
    } catch (photoErr) {
      // Don't fail the whole document if the photo is corrupt — just log
      // and continue without it. User still gets their CV.
      console.warn("[document-renderer] DOCX photo embed failed:", (photoErr as Error).message);
    }
  }

  if (input.title) {
    paragraphs.push(
      new Paragraph({
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: input.title, bold: true })],
      }),
    );
    paragraphs.push(new Paragraph({ children: [new TextRun("")] })); // spacer
  }

  paragraphs.push(...bodyToDocxParagraphs(input.body));

  if (input.footer) {
    paragraphs.push(new Paragraph({ children: [new TextRun("")] }));
    paragraphs.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({
            text: input.footer,
            italics: true,
            color: "888888",
            size: 18, // half-points; 18 = 9pt
          }),
        ],
      }),
    );
  }

  // File-properties metadata: keep it neutral so the recruiter cannot
  // read "CV Fix Lite" from the Word file Properties pane. Even if a
  // title arg is passed, we override it to a generic value here — the
  // visible body is what matters and that's already controlled above.
  const doc = new Document({
    creator: "WorkAbroad Hub",
    title: "Document",
    description: "Career document",
    sections: [{ children: paragraphs }],
  });

  return Packer.toBuffer(doc);
}

// ─── PDF ──────────────────────────────────────────────────────────────────────

export function renderPdf(input: RenderInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 50 });
      const chunks: Buffer[] = [];
      doc.on("data", (c) => chunks.push(c));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // 2026-07 (photo embed): draw the candidate's photo at top-right BEFORE
      // any text so the text flows naturally beneath it. Clipped to a rounded
      // rectangle so it reads as warm/professional rather than a stark
      // passport-booth cutout. Size = 90pt (~1.25 inches), tucked into the
      // top-right corner with 6pt breathing room from the page edge.
      // Silently skipped on any decode error — CV still generates.
      const photoSize = 90;
      const photoX = doc.page.width  - doc.page.margins.right - photoSize;
      const photoY = doc.page.margins.top - 20; // sit slightly higher than title baseline
      let photoDrawn = false;
      if (input.photo?.buffer && input.photo.buffer.length > 0) {
        try {
          doc.save();
          // Rounded-rectangle clipping path — gives it a soft edge without
          // being goofy about it. 6pt radius = subtle but human.
          doc.roundedRect(photoX, photoY, photoSize, photoSize, 6).clip();
          doc.image(input.photo.buffer, photoX, photoY, {
            width: photoSize,
            height: photoSize,
            // "cover" would be nicer but pdfkit uses "fit"/"cover" via fit/cover
            // props on some versions. Use fit which centres the image within
            // the bounding box preserving aspect ratio.
            fit: [photoSize, photoSize],
            align: "center",
            valign: "center",
          });
          doc.restore();
          // Add a subtle border ring OUTSIDE the clip so it draws on top.
          doc
            .roundedRect(photoX, photoY, photoSize, photoSize, 6)
            .lineWidth(0.75)
            .strokeColor("#e2e8f0")
            .stroke();
          photoDrawn = true;
        } catch (photoErr) {
          console.warn("[document-renderer] PDF photo embed failed:", (photoErr as Error).message);
        }
      }

      // When a photo is drawn, push the text cursor down a bit so the first
      // paragraph doesn't overlap the photo. Without this, the recruiter sees
      // the name/heading TUCKED under the image which looks janky.
      if (photoDrawn) {
        doc.y = photoY + photoSize + 10;
      }

      // 2026-08 (Tony's "ugly CV" complaint): brand palette — dark navy for
      // section headers reads as premium + professional across every ATS.
      // Body stays near-black for max readability. Muted grey for subtle
      // dividers under H2s. All ATS-safe (renders as plain text on parse).
      const COLOR_HEADING = "#0f172a";     // slate-900 — deep navy
      const COLOR_BODY    = "#1e293b";     // slate-800 — near-black, softer than pure #000
      const COLOR_ACCENT  = "#0f766e";     // teal-700 — for H2 section headers
      const COLOR_RULE    = "#cbd5e1";     // slate-300 — subtle divider under H2s

      if (input.title) {
        doc
          .font("Helvetica-Bold")
          .fontSize(22)
          .fillColor(COLOR_HEADING)
          .text(input.title, { align: "center" });
        doc.moveDown(0.8);
      }

      const lines = input.body.replace(/\r\n/g, "\n").split("\n");
      for (const raw of lines) {
        const line = raw.trim();
        if (!line) {
          doc.moveDown(0.5);
          continue;
        }
        // Headings — each one explicitly closes any previous text run by
        // setting continued:false (defensive against pdfkit state leak).
        if (line.startsWith("### ")) {
          doc.moveDown(0.3);
          doc.font("Helvetica-Bold").fontSize(11.5)
             .fillColor(COLOR_HEADING)
             .text(line.slice(4), { continued: false });
          doc.moveDown(0.2);
        } else if (line.startsWith("## ")) {
          // 2026-08: section headers now get colored + a subtle underline
          // rule. Elevates the visual quality without adding any binary
          // dependency (still pure pdfkit, still ATS-parseable).
          doc.moveDown(0.5);
          doc.font("Helvetica-Bold").fontSize(13.5)
             .fillColor(COLOR_ACCENT)
             .text(line.slice(3).toUpperCase(), { continued: false });
          // Underline rule across the content width
          const ruleY = doc.y + 1;
          doc.strokeColor(COLOR_RULE).lineWidth(0.5)
             .moveTo(doc.page.margins.left, ruleY)
             .lineTo(doc.page.width - doc.page.margins.right, ruleY)
             .stroke();
          doc.moveDown(0.4);
          doc.fillColor(COLOR_BODY);
        } else if (line.startsWith("# ")) {
          doc.font("Helvetica-Bold").fontSize(18)
             .fillColor(COLOR_HEADING)
             .text(line.slice(2), { continued: false });
          doc.moveDown(0.5);
        } else if (/^[*-]\s/.test(line)) {
          // Slight left-indent for bullets so they visually distinguish
          // from paragraph text. Bullet char uses en-space for tighter
          // alignment than double-space.
          doc
            .font("Helvetica").fontSize(10.5)
            .fillColor(COLOR_BODY)
            .text("• " + line.replace(/^[*-]\s/, ""), {
              continued: false,
              indent: 12,
            });
        } else {
          // Render inline bold spans (**bold**). Filter empty fragments first,
          // then use index-based iteration to set continued correctly on the
          // FINAL part. Previously used indexOf() which returned the first
          // occurrence — when the line ended with a "**word**" span, the empty
          // trailing fragment got continued:true and bled into the next line.
          const parts = line
            .split(/(\*\*[^*]+\*\*)/)
            .filter((p) => p && p.length > 0);

          if (parts.length === 0) {
            doc.moveDown(0.5);
            continue;
          }

          parts.forEach((part, idx) => {
            const isBold = part.startsWith("**") && part.endsWith("**");
            const text = isBold ? part.slice(2, -2) : part;
            const isLastPart = idx === parts.length - 1;
            doc
              .font(isBold ? "Helvetica-Bold" : "Helvetica")
              .fontSize(10.5)
              .fillColor(isBold ? COLOR_HEADING : COLOR_BODY)
              .text(text, { continued: !isLastPart });
          });
        }
      }

      if (input.footer) {
        doc.moveDown(2);
        doc
          .font("Helvetica-Oblique")
          .fontSize(9)
          .fillColor("#888")
          .text(input.footer, { align: "center" });
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
