/**
 * Application Materials AI Pipeline — BullMQ Queue
 * ─────────────────────────────────────────────────
 * Drives the full per-application processing flow:
 *
 *   queued → analyzing → generating → materials_ready   (happy path)
 *                                   → failed            (after 3 retries)
 *
 * Worker steps:
 *   1. Scrape + GPT-analyze the job posting URL
 *   2. GPT-generate tailored CV + cover letter
 *   3. Build PDF buffers (pdfkit)
 *   4. Upload PDFs to Supabase Storage → get public URLs
 *   5. Persist results + flip status → materials_ready
 *   6. Push WebSocket event + in-app notification + WhatsApp message
 */

import { Queue, Worker, type Job } from "bullmq";
import PDFDocument                 from "pdfkit";
import { redisConnection }         from "./redis";
import { trackJobCompleted, trackJobFailed } from "./aiStats";

export const QUEUE_NAME = "application-materials";

// ── Job payload ────────────────────────────────────────────────────────────────

export interface AppQueueJobData {
  applicationId: string;
  userId:        string;
}

// ── Queue (producer side) ──────────────────────────────────────────────────────

export const appQueue = new Queue<AppQueueJobData>(QUEUE_NAME, {
  connection: redisConnection,
  defaultJobOptions: {
    attempts:  3,
    backoff:   { type: "exponential", delay: 15_000 },
    removeOnComplete: { count: 100 },
    removeOnFail:     { count: 200 },
  },
});

// ── PDF helpers ────────────────────────────────────────────────────────────────

function buildPdfBuffer(headerLine: string, body: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc    = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data",  (c: Buffer) => chunks.push(c));
    doc.on("end",   () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(16).font("Helvetica-Bold").text(headerLine, { align: "center" });
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(1);
    doc.fontSize(11).font("Helvetica").text(body, { lineGap: 4 });
    doc.moveDown(2);
    doc.fontSize(8).fillColor("#888888").text(
      `Generated by WorkAbroad Hub · ${new Date().toLocaleDateString("en-KE", { dateStyle: "long" })}`,
      { align: "center" },
    );
    doc.end();
  });
}

// ── Storage upload ─────────────────────────────────────────────────────────────

const STORAGE_BUCKET = "application-materials";

async function uploadPdf(
  userId: string,
  applicationId: string,
  docType: "cv" | "cover_letter",
  buffer: Buffer,
): Promise<string | null> {
  try {
    const { supabase } = await import("../supabaseClient");
    const path = `${userId}/${applicationId}/${docType}.pdf`;

    // Ensure bucket exists (idempotent — fails silently if it already exists)
    await supabase.storage.createBucket(STORAGE_BUCKET, { public: true }).catch(() => {});

    const { error } = await supabase.storage
      .from(STORAGE_BUCKET)
      .upload(path, buffer, { contentType: "application/pdf", upsert: true });

    if (error) {
      console.warn(`[AppQueue] Storage upload failed (${docType}):`, error.message);
      return null;
    }

    const { data } = supabase.storage.from(STORAGE_BUCKET).getPublicUrl(path);
    return data?.publicUrl ?? null;
  } catch (err: any) {
    console.warn(`[AppQueue] Storage error (${docType}):`, err?.message);
    return null;
  }
}

// ── Worker ─────────────────────────────────────────────────────────────────────

export function startAppWorker() {
  const worker = new Worker<AppQueueJobData>(
    QUEUE_NAME,
    async (job: Job<AppQueueJobData>) => {
      const { applicationId, userId } = job.data;

      const { storage }            = await import("../storage");
      const { db }                 = await import("../db");
      const { userCareerProfiles } = await import("@shared/schema");
      const { eq }                 = await import("drizzle-orm");

      // ── 0. Load fresh application + user ───────────────────────────────────
      const application = await storage.getUserJobApplicationById(applicationId);
      if (!application) throw new Error(`Application ${applicationId} not found`);

      const user = await storage.getUserById(userId);
      if (!user) throw new Error(`User ${userId} not found`);

      const jobStartMs = Date.now();

      console.log(
        `[AppQueue] START | appId=${applicationId} | userId=${userId} | "${application.jobTitle}"`,
      );

      // ── 1. Analyze job posting ─────────────────────────────────────────────
      await storage.updateUserJobApplication(applicationId, {
        status:        "analyzing",
        statusMessage: "Scraping and analyzing the job posting…",
      });

      let jobAnalysis: any;
      const jobUrl = (application as any).jobUrl
        ?? (application as any).job_url
        ?? (application as any).intakeData?.job_url;

      if (jobUrl) {
        try {
          const { analyzeJob } = await import("../services/job-analyzer");
          jobAnalysis = await analyzeJob(jobUrl);
          console.log(
            `[AppQueue] Analyzed | title="${jobAnalysis.title}" @ ${jobAnalysis.company}`,
          );
        } catch (err: any) {
          console.warn(`[AppQueue] analyzeJob failed (using stored metadata):`, err?.message);
        }
      }

      // Fallback when scraping fails or no URL provided
      const resolvedJob = jobAnalysis ?? {
        id:              application.id,
        title:           application.jobTitle   ?? "Position",
        company:         application.companyName ?? "Company",
        country:         application.targetCountry ?? "Kenya",
        description:     (application as any).jobDescription ?? "",
        keywords:        [],
        required_skills: [],
        nice_to_have:    [],
        company_culture: "",
        tone:            "professional",
        seniority:       "mid",
        analyzed_at:     new Date().toISOString(),
      };

      // ── 2. Generate CV + Cover Letter ──────────────────────────────────────
      await storage.updateUserJobApplication(applicationId, {
        status:        "generating",
        statusMessage: "AI is writing your tailored CV and cover letter…",
      });

      const pack     = await storage.getUserApplicationPackById(application.userPackId).catch(() => null);
      const packType = (pack as any)?.packType ?? "standard";

      const [careerProfile] = await db
        .select()
        .from(userCareerProfiles)
        .where(eq(userCareerProfiles.userId, userId))
        .catch(() => [null]);

      const {
        generateJobTailoredCV,
        generateCoverLetter,
        generateInterviewPrep,
      } = await import("../services/application-materials");

      const [cv, coverLetter, interviewPrep] = await Promise.all([
        generateJobTailoredCV(user as any, careerProfile ?? null, resolvedJob, packType),
        generateCoverLetter(user as any, careerProfile ?? null, resolvedJob),
        generateInterviewPrep(user as any, careerProfile ?? null, resolvedJob),
      ]);

      console.log(
        `[AppQueue] Generated | cv=${cv.length} chars | cl=${coverLetter.length} chars | ` +
        `answers=${interviewPrep.tailoredAnswers.length} | suggestions=${interviewPrep.cvSuggestions.length}`,
      );

      // ── 3. Build PDFs ──────────────────────────────────────────────────────
      const [cvBuf, clBuf] = await Promise.all([
        buildPdfBuffer(
          `Curriculum Vitae — ${resolvedJob.title}`,
          cv,
        ),
        buildPdfBuffer(
          `Cover Letter — ${resolvedJob.title} at ${resolvedJob.company}`,
          coverLetter,
        ),
      ]);

      // ── 4. Upload to Supabase Storage ──────────────────────────────────────
      const [cvUrl, coverLetterUrl] = await Promise.all([
        uploadPdf(userId, applicationId, "cv",           cvBuf),
        uploadPdf(userId, applicationId, "cover_letter", clBuf),
      ]);

      if (cvUrl)          console.log(`[AppQueue] CV uploaded  → ${cvUrl}`);
      if (coverLetterUrl) console.log(`[AppQueue] CL uploaded  → ${coverLetterUrl}`);

      // ── 5. Persist results ─────────────────────────────────────────────────
      const materials = {
        cv,
        coverLetter,
        tailoredAnswers: interviewPrep.tailoredAnswers,
        cvSuggestions:   interviewPrep.cvSuggestions,
        cvUrl:           cvUrl          ?? undefined,
        coverLetterUrl:  coverLetterUrl ?? undefined,
        generatedAt:     new Date().toISOString(),
        jobAnalysis:     resolvedJob,
      };

      await storage.updateUserJobApplication(applicationId, {
        preparedMaterials: materials as any,
        status:            "materials_ready",
        statusMessage:     "Your CV and cover letter are ready to download.",
      });

      // ── 6. Notify user ─────────────────────────────────────────────────────

      // In-app notification
      await storage.createUserNotification({
        userId,
        type:    "success",
        title:   "Application Materials Ready!",
        message: `Your tailored CV and cover letter for ${resolvedJob.title} at ${resolvedJob.company} are ready.`,
        isRead:  false,
      }).catch(() => {});

      // WebSocket push
      try {
        const { notifyApplicationReady } = await import("../websocket");
        notifyApplicationReady(userId, applicationId, {
          status:         "materials_ready",
          jobTitle:       resolvedJob.title,
          company:        resolvedJob.company,
          cvUrl:          cvUrl          ?? undefined,
          coverLetterUrl: coverLetterUrl ?? undefined,
        });
      } catch (wsErr: any) {
        console.warn("[AppQueue] WS notify failed:", wsErr?.message);
      }

      // Browser push notification
      try {
        const { sendUserPushNotification } = await import("../services/application-materials");
        await sendUserPushNotification(userId, {
          title: "Materials Ready!",
          body:  `Your CV and cover letter for ${resolvedJob.title} are ready to download.`,
        });
      } catch (pushErr: any) {
        console.warn("[AppQueue] Push notify failed:", pushErr?.message);
      }

      // WhatsApp
      try {
        const phone =
          (user as any).phone ??
          (user as any).phoneNumber ??
          (user as any).whatsapp_number;

        if (phone) {
          const { sendWhatsApp } = await import("../sms");
          await sendWhatsApp(
            phone,
            `✅ *WorkAbroad Hub*\n\nYour tailored CV and cover letter for *${resolvedJob.title}* at *${resolvedJob.company}* are ready!\n\nLogin to download and submit → https://workabroad.hub`,
          );
        }
      } catch (waErr: any) {
        console.warn("[AppQueue] WhatsApp failed:", waErr?.message);
      }

      // Track timing for the stats dashboard
      trackJobCompleted(Date.now() - jobStartMs).catch(() => {});

      console.log(
        `[AppQueue] COMPLETE | appId=${applicationId} | elapsed=${Date.now() - jobStartMs}ms`,
      );
    },
    { connection: redisConnection, concurrency: 3 },
  );

  // ── Failure handler ────────────────────────────────────────────────────────
  worker.on("failed", async (job, err) => {
    if (!job) return;
    const { applicationId, userId } = job.data;
    const maxAttempts = job.opts.attempts ?? 3;

    console.error(
      `[AppQueue] Job ${job.id} failed (attempt ${job.attemptsMade}/${maxAttempts}):`,
      err.message,
    );

    // Only flip to "failed" after all retries are exhausted
    if (job.attemptsMade >= maxAttempts) {
      trackJobFailed().catch(() => {});
      const { storage } = await import("../storage");

      await storage.updateUserJobApplication(applicationId, {
        status:        "failed",
        statusMessage: "AI generation failed. Please try again.",
      }).catch(() => {});

      await storage.createUserNotification({
        userId,
        type:    "error",
        title:   "Material Generation Failed",
        message: "We encountered an error generating your application materials. Please try again.",
        isRead:  false,
      }).catch(() => {});

      // WS error push
      try {
        const { notifyApplicationReady } = await import("../websocket");
        notifyApplicationReady(userId, applicationId, { status: "failed" });
      } catch { /* best-effort */ }
    }
  });

  worker.on("completed", (job) => {
    console.log(`[AppQueue] Worker completed job ${job.id} ✓`);
  });

  console.log("[AppQueue] BullMQ worker started (concurrency=3, 3 retries, exponential backoff)");
  return worker;
}
